# Generated by Django 6.0.4 on 2026-05-04 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0004_post_reminder_review_favoriteshop_recentviewproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField()),
                ('receive_type', models.CharField(choices=[('pickup', '픽업'), ('delivery', '배송')], default='pickup', max_length=20)),
                ('request_message', models.TextField(blank=True)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', '주문 대기'), ('paid', '결제 완료'), ('accepted', '판매자 수락'), ('rejected', '판매자 거절'), ('preparing', '제작 중'), ('ready', '픽업/배송 준비'), ('completed', '완료'), ('cancel_requested', '취소 요청'), ('cancelled', '취소 완료'), ('refunded', '환불 완료')], default='pending', max_length=30)),
                ('cancel_reason', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.shop')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shops.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
