# Generated by Django 6.0.4 on 2026-05-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('product_type', models.CharField(choices=[('bouquet', '꽃다발'), ('basket', '꽃바구니'), ('plant', '화분'), ('custom', '커스텀')], default='custom', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='shops.shop')),
            ],
        ),
    ]
